### ISSUE TITLE
locality names in meta data

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-data#117]
in the `meta/wof-locality-latest.csv` file the `name` field seems to refer to the parent instead of the `locality`?

eg.

```
"174.765751,-41.254068,174.769356,-41.251586",,bea774820cf735ae5017240c12c365d1,-41.252994,174.767834,101918055,NZ,1444274777,-41.253129,174.767945,Wellington,85687233,101/918/055/101918055.geojson,quattroshapes,,

"174.788964,-41.259048,174.790786,-41.257307",,dc2a67ca388c298d909807c19959ae3b,-41.258177,174.789927,101918051,NZ,1444274777,-41.258242,174.790015,Wellington,85687233,101/918/051/101918051.geojson,quattroshapes,,
```

**Comment by thisisaaronland** [comment]
Nope. This are two different records for Wellington that, by all appearances are the same place but with different geometries which is weird (cc @nvkelso) :

https://whosonfirst.mapzen.com/spelunker/id/101918051/
https://whosonfirst.mapzen.com/spelunker/id/101918055/

But the meta files are being written correctly.

**Comment by missinglink** [comment]
neither of those 2 places are wellington, they are both children of the wellington region

**Comment by thisisaaronland** [comment]
They are part of an exploded multi-polygon. See also: https://github.com/whosonfirst/whosonfirst-data/issues/118
