### ISSUE TITLE
Clean up encoding / names for "Ð¢ÐµÑÐ½Ð¾Ð¿ÑÐ»ÑÑÑÐºÐ¸Ð¹"

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-data#120]
https://whosonfirst.mapzen.com/spelunker/id/102088355/

I know, right...

![screen shot 2015-10-21 at 15 26 07](https://cloud.githubusercontent.com/assets/12658759/10652038/1a959918-7808-11e5-9504-36298d69b586.png)

**Comment by stepps00** [comment]
This issue was resolved in https://github.com/whosonfirst/whosonfirst-data/issues/244.

Adding 'merge me' tag and assigning to @thisisaaronland to confirm we're OK to close this issue.

**Comment by thisisaaronland** [comment]
Yes, this appears to be fixed.
