### ISSUE TITLE
Golden Gate Park (SF) is too small, fix all the SF hoods

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-data#125]
https://whosonfirst.mapzen.com/spelunker/id/85865925/

![screen shot 2015-10-26 at 08 05 46](https://cloud.githubusercontent.com/assets/12658759/10732677/65eaebc6-7bb8-11e5-9f42-806f07a43260.png)

**Comment by nvkelso** [comment]
See also: 

* https://www.flickr.com/photos/ke6cat/6079436254/in/album-72157627357720745/

**Comment by stepps00** [comment]
@nvkelso the [neighbourhood record](https://whosonfirst.mapzen.com/spelunker/id/85865925/) of Golden Gate Park matches surrounding neighbourhood polygons. Should this record's geometry change along with the [venue record](https://whosonfirst.mapzen.com/spelunker/id/588411547/) for Golden Gate Park?

**Comment by nvkelso** [comment]
The potential datasource you mention is more on the `macrohood` level of detail then that found in WOF currently. But sourcing **Golden Gate Park** shape by itself would work just for this issue. But if you mod this record, you need to also mod the neighbouring features so we preserve continuous coverage. Which leads into...

Longer term, I'd like to take the shapes in [my Flickr post](https://www.flickr.com/photos/ke6cat/6079436254/in/album-72157627357720745/) and clean them up and import them into WOF.

(You can ignore the WOF venue for now.)

**Comment by stepps00** [comment]
Updating just the Golden Gate Park geometry would mean the [Richmond District](https://whosonfirst.mapzen.com/spelunker/id/85869003/#15/37.7780/-122.4893) record would also need to be updated. Enlarging the Golden Gate Park record would also cause an overlap with several other neighbourhood records ([Central Sunset](https://whosonfirst.mapzen.com/spelunker/id/85851557/#15/37.7624/-122.4895), [Central RIchmond](https://whosonfirst.mapzen.com/spelunker/id/85844431/#14/37.7786/-122.4779), [Outset](https://whosonfirst.mapzen.com/spelunker/id/85887447/#14/37.7596/-122.5067), etc). I will create a new branch with an updated geometry, but it's probably best to discuss importing new shapes, as it would lead to fewer problems and more accurate coverage.

**Comment by nvkelso** [comment]
Looking at SF public data:

- [SF-Find-Neighborhoods](https://data.sfgov.org/Geographic-Locations-and-Boundaries/SF-Find-Neighborhoods/pty2-tcw4) seem like the best features & geometries to import with public license. 
- [SF Realtor-Neighborhoods](https://data.sfgov.org/Geographic-Locations-and-Boundaries/Realtor-Neighborhoods/5gzd-g9ns), seems less good, and says public that should be verified because, well, Realtors. 
- Some sort of [neighbourhood clusters](https://data.sfgov.org/Geographic-Locations-and-Boundaries/Analysis-Neighborhoods/p5b7-5n3h), background 411 only.

(below) SF Find Neighbourhoods

<img width="579" alt="screen shot 2016-05-18 at 11 02 01" src="https://cloud.githubusercontent.com/assets/853051/15369573/13ff73e6-1ce8-11e6-80a9-e6e23322e7c5.png">

**Comment by stepps00** [comment]
Agreed that the [SF-Find-Neighborhoods](https://data.sfgov.org/Geographic-Locations-and-Boundaries/SF-Find-Neighborhoods/pty2-tcw4) is likely the best source for San Francisco neighborhood data. This dataset is more accurate and granular than other options. Currently, WOF contains [164 neighbourhood records](https://whosonfirst.mapzen.com/spelunker/id/85922583/descendants/?placetype=neighbourhood&placetype=neighbourhood#12/37.7573/-122.4315) (several outdated or overlapping), while the [SF Open Data](https://data.sfgov.org/Geographic-Locations-and-Boundaries/SF-Find-Neighborhoods/pty2-tcw4) source contains 117.

**Comment by nvkelso** [comment]
Great!

1. Please propose concordances by attributing the SF Find Neighbourhoods with WOF `id` values so we can compare and contrast and create an import plan. 
2. I suspect some of the WOF `neighbourhoods` could be demoted to `microhood`, propose those by noting the new WOF neighbourhood `parent_id`.
3. Others we should keep but cut out of the SF Find shapes, also propose those by the WOF records locally with a boolean (e.g.: `preserve` column with a value of `1`).

**Comment by stepps00** [comment]
Closing this issue out, as https://github.com/whosonfirst/whosonfirst-data/issues/316 was created to take care of SF neighbourhoods as a whole (not just GGP).
