### ISSUE TITLE
Does the Financial District (SF) really include Treasure Island

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-data#126]
I mean maybe it's like "The City" in London, but probably not...

https://whosonfirst.mapzen.com/spelunker/id/85865899/

![screen shot 2015-10-26 at 08 06 46](https://cloud.githubusercontent.com/assets/12658759/10732727/9c34ae10-7bb8-11e5-9ead-058c8172a7e7.png)

**Comment by nvkelso** [comment]
Treasure Island is special and missing. While we generally don't want to mess with neighbourhood shape right now (there are some systemic issues to work thru), let's make an exception here:

- Make a new record for Treasure Island.
- Cut off Financial District island chunk and give it to new record.
- Cut off Presidio Heights (?) chunk and give it to new record.

**Comment by nvkelso** [comment]
Related: https://github.com/whosonfirst/whosonfirst-data/issues/127
