### ISSUE TITLE
Presidio Heights (SF) has delusions of grandeur

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-data#127]
It's like when Alberta said they should build a navy....

https://whosonfirst.mapzen.com/spelunker/id/85865911/

![screen shot 2015-10-26 at 08 10 03](https://cloud.githubusercontent.com/assets/12658759/10732824/1851c226-7bb9-11e5-9285-3df3075bd955.png)

**Comment by nvkelso** [comment]
And the related Financial District PR: https://github.com/whosonfirst/whosonfirst-data/issues/283
