### ISSUE TITLE
Duplicate macrohood ids?

### ISSUE THREAD

**Issue by rmarianski** [whosonfirst/whosonfirst-data#138]
Seems like there are duplicate macrohood ids here:

https://github.com/whosonfirst/whosonfirst-data/blob/4b51bce1f096b4d9c2a5e31317d5e9afb674bcb0/meta/wof-macrohood-latest.csv

**Comment by thisisaaronland** [comment]
Specifics?

**Comment by rmarianski** [comment]
There are 2 rows there, each have the same id: 85892915

The 2nd row does have a different path, namely 102/147/495/102147495.geojson. When looking at the raw data using that path, it has an `id` of 102147495 but a `wof:id` of 85892915.

**Comment by thisisaaronland** [comment]
Oh interesting. So two things:

1) The data is buggy. I will fix shortly.
2) One of those is "superseded" by the other, so you should probably be filtering on things whose "superseded_by" property is not null. 

(Which in this case is still both of them because... computers?)

**Comment by thisisaaronland** [comment]
Fixed, pushed to master.
