### ISSUE TITLE
Missing label lat/lng for macrohood

### ISSUE THREAD

**Issue by rmarianski** [whosonfirst/whosonfirst-data#140]
`lbl_latitude` and `lbl_longitude` are set to 0 for the BoCoCa macrohood (in the meta csv):

https://github.com/whosonfirst/whosonfirst-data/blob/0fd8c2c372cac3410aa77edef2a696f3772fd442/meta/wof-macrohood-latest.csv

And missing from the raw geojson:

https://whosonfirst.mapzen.com/data/102/147/495/102147495.geojson

Possibly related to https://github.com/whosonfirst/whosonfirst-data/issues/129 ?

**Comment by thisisaaronland** [comment]
Huh. No, that just got lost in the shuffle.

*tasteful muzak plays*

**Comment by thisisaaronland** [comment]
Fixed. Sorry for the hiccup.
