### ISSUE TITLE
La Lengua needs to supersede Transmission

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#143]
We added La Lengua a while back. But we should have superseded Transmission (preferred La Lengua instead of Transmission) at the same time.

Copy over the records, though.

La Lengua:

* https://github.com/whosonfirst/whosonfirst-data/blob/c917e6ca3f0f4f7e52ab226a367ad5b854b2daed/data/858/874/69/85887469.geojson

Transmission:

* https://github.com/whosonfirst/whosonfirst-data/blob/c917e6ca3f0f4f7e52ab226a367ad5b854b2daed/data/858/874/69/85887469.geojson

**Comment by thisisaaronland** [comment]
La Lengua is actually 102112179, but yes.
