### ISSUE TITLE
Edison, New Jersey, USA (locale) is missing

### ISSUE THREAD

**Issue by plasticglobe** [whosonfirst/whosonfirst-data#150]
Edison, New Jersey is missing as a locale in New Jersey, USA. There are two neighborhoods, North and South Edison (1), but no corresponding locale. I think these neighborhoods may correspond to the city of Edison, NJ, but that is purely guesswork on my part.

Background: I compared the list of cities available in Who's on First to those in the "top US cities by population" in Wikipedia (2), a list of cities in the US with 2014 census populations greater than 100,000. Once I resolved name mismatches and the city-is-a-county problem, there was only one town missing: Edison, NJ. I searched through Who's on First database using the Spelunker, and I found three neighborhoods called Edison, but only those listed above were in Middlesex county.

1) https://whosonfirst.mapzen.com/spelunker/id/102087417/descendants/
2) https://en.wikipedia.org/wiki/List_of_United_States_cities_by_population

**Comment by nvkelso** [comment]
Hi, thanks for letting us know about Edison! 

Reading more in that Wikipedia link, 

```
In the state of New Jersey, townships are full-fledged municipalities on par with any
town, city, borough, or village. "Annual Estimates of the Resident Population for 
Minor Civil Divisions, by County: April 1, 2010 to July 1, 2014". 2014 Census 
Population Estimates. U.S. Census Bureau, Population Division. May 2015. 
Retrieved May 22, 2015.
```

So we should have **Edison** at the `local_admin` level in Who's On First. 

I find it in the data here:

https://github.com/whosonfirst/whosonfirst-data/blob/master/data/404/478/273/404478273.geojson

But searching in the Spelunker seems to have a problem. I've filed this to debug that: https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/11.

You should have been able to walk back to the **Edison** `localadmin` in the **North Edison** `neighbourhood` record's hierarchy. But that part is missing and I've filed https://github.com/whosonfirst/whosonfirst-data/issues/151.
