### ISSUE TITLE
Please expose 2-character US/CA state/province codes

### ISSUE THREAD

**Issue by trescube** [whosonfirst/whosonfirst-data#154]
Pelias uses these codes.  The conversation in flowdock says that these codes have already been concorded but I wanted to make it official that the search team uses them.  Sorry if this is a duplicate, I did a cursory check of existing issues and didn't see anything.

**Comment by thisisaaronland** [comment]
Just to clarify you want the short codes in the records for the regions themselves, yes?

**Comment by stephenkhess** [comment]
Correct

**Comment by riordan** [comment]
:+1:

**Comment by thisisaaronland** [comment]
This was added ... sometime last week.
