### ISSUE TITLE
newline in name field, name repetition

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-data#156]
```bash
$ grep "Kecamatan Pendopo" wof-locality-latest.csv
```

```bash
"102.938387,-3.802044,102.956388,-3.783962",03721650da7b4ebd0e54e8a0f90c1794,,63038d7674a963b3d0b349efe250be9a,-3.793003,102.947388,102022691,ID,1444277344,-3.793003,102.947388,"Kecamatan Pendopo
Kecamatan Pendopo",102073279,102/022/691/102022691.geojson,quattroshapes,,
```

this record "Kecamatan Pendopo" also seems to have it's name repeated

**Comment by nvkelso** [comment]
It looks like this is a problem in two properties on [102073279](https://whosonfirst.mapzen.com/spelunker/id/102022691/):

    "wof:name":"Kecamatan Pendopo\r\nKecamatan Pendopo",
    "qs:loc":"Kecamatan Pendopo\r\nKecamatan Pendopo",

The Spelunker handles it fine (replacing both \r and \n with white space).

**Comment by nvkelso** [comment]
It'll take a little bit of time for this to show up in the metafile for localities, btw.
