### ISSUE TITLE
Baykonur is a top-level lease area (not a region of Kazakhstan)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#16]
wof_id	iso	name
85681265	-1	Baykonur lease in Qyzylorda	

data/856/812/65/85681265.geojson

proposed parent:
85632685 (Russia)
parent now:
85632307 (Kaz)

**Comment by stepps00** [comment]
`wof:parent_id` field value is now `85632685`.

OK to close this issue? @nvkelso

**Comment by nvkelso** [comment]
Yep, closing.
