### ISSUE TITLE
Capitol Hill neighborhood in Seattle dupes & issues

### ISSUE THREAD

**Issue by bcamper** [whosonfirst/whosonfirst-data#162]
Numerous issues with Capitol Hill neighborhood in Seattle:

- Has 3 entries:
  - Capitol Hill: https://whosonfirst.mapzen.com/spelunker/id/85809401/
  - Capit**a**l Hill (misspelling): https://whosonfirst.mapzen.com/spelunker/id/85882415/
  - Broadway: https://whosonfirst.mapzen.com/spelunker/id/85807733/

- The one labelled Broadway is the closest representation of Capitol Hill of the 3 (Broadway is the major cultural street running through Capitol Hill, but it is not a neighborhood). 

- The "Capitol Hill" entry is the least accurate of the 3.

- Capitol Hill proper is probably closest to a combination of "Broadway" and "Capital Hill" (sic). Though these still breach multiple surrounding neighborhoods, in particular Montlake to the north.

First priority should be to consolidate and fix spelling.

**Comment by dphiffer** [comment]
Similar kind of situation in Prospect Park South:
https://whosonfirst.mapzen.com/spelunker/id/85865585/
https://whosonfirst.mapzen.com/spelunker/id/85865585/

**Comment by nvkelso** [comment]
Re-opening, because the PR isn't merged yet.

**Comment by stepps00** [comment]
Closing because the PR was merged to master.
