### ISSUE TITLE
uppercase names

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-data#164]
```bash
wof:id wof:name

85632711 UNDOF
85681873 ACRE
85681879 ALAGOAS
85681885 AMAZONAS
85681895 BAHIA
85681911 DISTRITO FEDERAL
85681921 ESPIRITO SANTO
85681941 MINAS GERAIS
85681947 MATO GROSSO DO SUL
85681955 MATO GROSSO
...

total 18376
```

https://gist.github.com/missinglink/e916f9783d634e5f940a

**Comment by thisisaaronland** [comment]
These have always been in QS but this is a useful list for batch-fixing.

**Comment by thisisaaronland** [comment]
Closing this - in the process of updating filenames it was discovered that there a bunch of files with are invalid JSON because ... ? ... but those will tracked separately.
