### ISSUE TITLE
Internal Consistency Check

### ISSUE THREAD

**Issue by trescube** [whosonfirst/whosonfirst-data#168]
I noticed that there are some instances in the data where the placetype inferred from a record's hierarchy doesn't match the placetype of the referenced id.  Here are a few examples of what I'm talking about:

id `85632161` (Macao) is a country according to wof:placetype.  It's hierarchy contains `country_id: 102191569`.  `102191569` is actually the id of Asia, a self-professed continent by wof:placetype.  

id `85667845` (Hammarland) is a region according to wof:placetype.  It's hierarchy contains `country_id: 85632789`.  `85632789` is actually the id of Åland Islands, a self-professed dependency by placetype.  

id `102064205` (no name) is a region according to wof:placetype.  It's hierarchy contains `country_id: 85633115`.  `85633115` does not appear to be a valid wof id.  

I have about 64k of these where the placetype according to hierarchy is not consistent with the placetypes of the referenced ids.  Our WoF importer walks the hierarchy of each row to be imported to flesh out the records written to ES.  We understand that when placetype "superseded" enters the mix, there are redirects involved, but perhaps we could get together to figure out the rules for walking up a hierarchy to establish names for Pelias records.

**Comment by thisisaaronland** [comment]
Yeah, someone of this is boot-strapping and some of it appears to be the result of some code errors along the way. 

The goal is for the hierarchies to all be sane and correct so there are backfills being scheduled. As a rule the parent_id should always be correct.

**Comment by stephenkhess** [comment]
So you're saying that we shouldn't rely upon hierarchy?

**Comment by thisisaaronland** [comment]
No, I am saying that there may still be bugs.

**Comment by thisisaaronland** [comment]
Closing this since I am pretty sure that the immediate concerns have been addressed and we've moved on to new bugs?
