### ISSUE TITLE
Make sure same country codes are used everywhere

### ISSUE THREAD

**Issue by peterneubauer** [whosonfirst/whosonfirst-data#171]
Hi there, I see `iso:country` = `sw` here: https://github.com/whosonfirst/whosonfirst-data/blob/master/data/101/752/283/101752283.geojson?short_path=cbe1115#L13

Shouldn't it be `SE` like in the rest of the dataset?

**Comment by thisisaaronland** [comment]
Yup, that's a bug - I will fix that record shortly and run a backfill to ensure the rest are correct.

Thanks for the heads up!
