### ISSUE TITLE
Parent of Cyprus in Europe, not -1

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#18]
wof_id	iso	name
85632437	CY	Cyprus

data/856/324/37/85632437.geojson

parent now: 
-1
parent proposed:
102191569 (Asia the continent)

_NOTE: NVK: 2016.05.16 corrected from "Europe", was correctly the Asia wof_id._

**Comment by hugovk** [comment]
This has been fixed: `wof:parent_id: "102191569"`

https://raw.githubusercontent.com/whosonfirst/whosonfirst-data/master/data/856/324/37/85632437.geojson

**Comment by nvkelso** [comment]
Looks like that was fixed, but the country is also (weirdly) also the continent_id value:

```
"wof:hierarchy":[
{
"continent_id":"102191569",
"country_id":"102191569"
}
```

**Comment by stepps00** [comment]
* Updated the record for Cyprus in the [most recent commit](https://github.com/whosonfirst/whosonfirst-data/pull/287). 

* Proposed ID above (`102191569`) is actually for the continent of Asia. Replaced record for Asia with record for Europe.

**Comment by stepps00** [comment]
Closing this issue, as detailed in [pull comments](https://github.com/whosonfirst/whosonfirst-data/pull/287). Records in WOF database are now correct.
