### ISSUE TITLE
Please add these Canadian province abbreviations

### ISSUE THREAD

**Issue by trescube** [whosonfirst/whosonfirst-data#190]
85682091: AB
85682123: NL
85682117: BC
85682065: NB
85682081: PE
85682085: MB
85682067: NT
85682075: NS
85682105: NU
85682057: ON
136251273: QC
85682113: SK
85682095: YT

**Comment by thisisaaronland** [comment]
Done. There is a generic tool for importing CSV files formatted as follows, for future reference.

```
id,subdivision
85682091,AB
85682123,NL
85682117,BC
```

**Comment by nvkelso** [comment]
@thisisaaronland Where is the script? I'd like to use it for the USA states, Brazil, and Australia.

**Comment by trescube** [comment]
FYI: @thisisaaronland already added US state abbreviations

**Comment by nvkelso** [comment]
@trescube That's great to hear :)
