### ISSUE TITLE
Investigate using Dat for dataset dissemination

### ISSUE THREAD

**Issue by riordan** [whosonfirst/whosonfirst-data#196]
[Dat](http://www.dat-data.com) is reaching a 1.0, and given the way we're moving with Who's on First, might be worth investigating as a successor to Git/Github for managing WoF files.

Dat was pitched as a "Git For Data", principally oriented around tabular datasets (think replacing civic data portals), but then the Alfred P. Sloan Foundation entered the picture and asked them to investigate scientific data use cases.

Now it's becoming a distributed version control / syncing protocol thats pretty data agnostic. Dropbox + bittorrent + versioning + distributed.

**Comment by nvkelso** [comment]
Most other Mapzen projects have a org/repo-with-org-name repo to store general comments like this, should we adopt that practice?

**Comment by thisisaaronland** [comment]
"repo-with-org-name" ?

**Comment by nvkelso** [comment]
whosonfirst/whosonfirst

(like pelias/pelias)

**Comment by thisisaaronland** [comment]
Sure.

**Comment by nvkelso** [comment]
Migrated to: https://github.com/whosonfirst/whosonfirst/issues/1.
