### ISSUE TITLE
add NFL Experience microhood (Howard, 3rd to 5th)

### ISSUE THREAD

**Issue by burritojustice** [whosonfirst/whosonfirst-data#198]
"geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -122.40054845809937,
              37.78502470943418
            ],
            [
              -122.40421235561371,
              37.782137498379704
            ],
            [
              -122.40416944026947,
              37.78210358039895
            ],
            [
              -122.40268349647522,
              37.783286460783195
            ],
            [
              -122.40264594554901,
              37.78326102269454
            ],
            [
              -122.40047335624693,
              37.78496111569183
            ],
            [
              -122.40054845809937,
              37.78502470943418
            ]
          ]
        ]
      }

**Comment by thisisaaronland** [comment]
https://whosonfirst.mapzen.com/spelunker/id/420564211/

**Comment by thisisaaronland** [comment]
See also:

https://whosonfirst.mapzen.com/spelunker/tags/superbowl50/
https://whosonfirst.mapzen.com/spelunker/tags/sportsball/
