### ISSUE TITLE
No record for Isle of Man

### ISSUE THREAD

**Issue by riordan** [whosonfirst/whosonfirst-data#200]
It's on the map, but not in the data

**Comment by nvkelso** [comment]
Could be an upstream error in Quattroshapes. We can import it from the raw State Department shapes in the Quattroshapes project, though.

**Comment by stepps00** [comment]
.geojson for the Isle of Man is in the following location:

https://github.com/whosonfirst/whosonfirst-data/tree/master/data/856/324/61
