### ISSUE TITLE
Bad encoding

### ISSUE THREAD

**Issue by trescube** [whosonfirst/whosonfirst-data#204]
https://whosonfirst.mapzen.com/spelunker/id/102080577/ is named 'LiptovskÃ½ MikulÃ¡Å¡'

**Comment by trescube** [comment]
In fact, there are 241 counties containing the character `½`

**Comment by dianashk** [comment]
Another one to add to the list:

https://whosonfirst.mapzen.com/spelunker/id/102049763/

**Comment by nvkelso** [comment]
Related: https://github.com/whosonfirst/whosonfirst-data/issues/49#issuecomment-191961532

**Comment by dianashk** [comment]
Found this encoding issue in a county

[the county of VÃ¶lkermarkt](https://whosonfirst.mapzen.com/spelunker/id/102049685/) should be `Voelkermarkt`

**Comment by thisisaaronland** [comment]
http://www.i18nqa.com/debug/utf8-debug.html

**Comment by thisisaaronland** [comment]
For good time, call Windows-1252...

```
>>> import geojson
>>> fh = open('data/102/080/577/102080577.geojson', 'r')
>>> data = geojson.load(fh)
>>> props = data['properties']
>>> print props['wof:name']
LiptovskÃ½ MikulÃ¡Å¡
>>> print props['wof:name'].encode('windows-1252')
Liptovský Mikuláš
>>> print props['wof:name'].encode('windows-1252').decode('utf-8')
Liptovský Mikuláš
```

So, that at least suggests a way to approach the problem. I will run some test code.

**Comment by dphiffer** [comment]
I � character encoding

**Comment by thisisaaronland** [comment]
So, a first pass yields 1019 records that are easy to fix, with basic encoding juggling (so "Kempten (AllgÃ¤u)" becomes "Kempten (Allgäu)") and a remaining 3098 records that are... character encoded.

Nothing is checked in because I have to run and want to do some more spot checking on the first batch. The remaining funky names... are character encoded.

**Comment by stepps00** [comment]
Closing, as this issue was taken care of in Issue #244.
