### ISSUE TITLE
Is 'Canadian' actually a locality in AU?

### ISSUE THREAD

**Issue by trescube** [whosonfirst/whosonfirst-data#207]
https://whosonfirst.mapzen.com/spelunker/id/101932703/

**Comment by nvkelso** [comment]
Yep, it is: https://en.wikipedia.org/wiki/Canadian,_Victoria

**Comment by thisisaaronland** [comment]
See also: https://www.youtube.com/watch?v=7k4cFMVfnCE

**Comment by thisisaaronland** [comment]
See also-er: https://www.youtube.com/watch?v=OJE3EgTGg9k

**Comment by trescube** [comment]
Ah, well we'll have to tighten up our searching and business rules then!
