### ISSUE TITLE
empires have no data

### ISSUE THREAD

**Issue by meetar** [whosonfirst/whosonfirst-data#213]
https://whosonfirst.mapzen.com/spelunker/placetypes/empire/

troll-data ಠ_ಠ

**Comment by thisisaaronland** [comment]
Be careful what you wish for, buddy.

**Comment by nvkelso** [comment]
For example, Puerto Rico should probably be a member of the United States empire. See: https://github.com/whosonfirst/whosonfirst-data/issues/39 instead of funky country and dependency & region setup we have today.

**Comment by nvkelso** [comment]
See "sovereignty" in Natural Earth for the rundown in the admin-0 layer). There should be around 10 of them.

- http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-details/
- Basically it amounts to: `Passports are issued by sovereign states, not countries.`
- http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_sovereignty.zip

**Comment by stepps00** [comment]
Noting that Issue #4 is in progress - the PR for that issue will add dependencies, disputes, and country records to their appropriate empire records.

**Comment by nvkelso** [comment]
This is a dup of #4, closing.
