### ISSUE TITLE
Remove (M) from Circular Head name in Australia

### ISSUE THREAD

**Issue by dianashk** [whosonfirst/whosonfirst-data#219]
[Circular Head (M)](https://whosonfirst.mapzen.com/spelunker/id/102049649/)

Should the `(M)` be part of the name?

**Comment by nvkelso** [comment]
Agree the ` (M)` should be removed. 

Background: The current name comes straight from Australian official data. Not sure why they're appending that, but it's not in common usage so we should remove it.
