### ISSUE TITLE
Alaskan county name change

### ISSUE THREAD

**Issue by trescube** [whosonfirst/whosonfirst-data#220]
According to https://en.wikipedia.org/wiki/Kusilvak_Census_Area,_Alaska

Wade Hampton Census Area (https://whosonfirst.mapzen.com/spelunker/id/102081013/) has changed names to Kusilvak Census Area.

**Comment by trescube** [comment]
This is very recent (as of 2015)

**Comment by nvkelso** [comment]
Good catch!

I think there were a couple more of these, too?

**Comment by stepps00** [comment]
County names changed according to section: 'Name and/or Code Changes or Corrections for Counties or County Equivalent Entities' in:

https://www.census.gov/geo/reference/county-changes.html
