### ISSUE TITLE
Sanity check QS points file

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-data#222]
Specifcally `quattroshapes_gazetteer_gn_then_gp_with_content.zip`. 

I went through the list and filtered out things with existing concordances (QS,GP or GN) and wrote them to separate files. The counts are:

```
wc -l qs-points-review-20160305-has-wof.csv
153723 
wc -l qs-points-review-20160305-no-wof.csv
365036
```

Of those without a concordance the place types break out as follows:

```
Town	152506
County	21048
HistoricalCounty	9
LocalAdmin	75185
UNKNOWN	88209
Suburb	26888
State	1136
Country	54
```

The CSV files themselves are available here:

http://whosonfirst.mapzen.com.s3.amazonaws.com/misc/qs-points-review-20160305-has-wof.csv.bz2
http://whosonfirst.mapzen.com.s3.amazonaws.com/misc/qs-points-review-20160305-no-wof.csv.bz2

**Comment by thisisaaronland** [comment]
Of the records with no concordances 9094 of them don't have geometries either. The placetype break down is:

```
cat qs-points-review-20160305-no-wof-no-geo.csv | awk -F ',' '{ print $4 }' | sort | uniq
County
HistoricalCounty
LocalAdmin
State
Town
```

**Comment by thisisaaronland** [comment]
Notes going forward:

* Skip `UNKNOWN`, for now
* Skip `Country`, for now
* Things for which QS has no data (in that country) should be blanket imported - list of countries to follow
* Things for which QS has uncertain-data (in that country) should be skipped for now - list of countries to follow

**Comment by thisisaaronland** [comment]
```
0 = no polygon data from any source. DO IMPORT GAZETTEER BLINDLY (edited)
1 = great open admin data via QS from gov't sources – don’t import this again
2 = suspect QS original data based on tile counting, known to miss many features, file a later issue to go back and sort these out
3 = suspect "open" data that's known to miss many features, file a later issue to go back and sort these out
```

**Comment by nvkelso** [comment]
CSV file with the final column matched to the above 0-3 legend:

[qs_gazetteer_import_strategy.txt](https://github.com/whosonfirst/whosonfirst-data/files/182967/qs_gazetteer_import_strategy.txt)

**Comment by nvkelso** [comment]
<img width="285" alt="screen shot 2016-03-21 at 12 43 18" src="https://cloud.githubusercontent.com/assets/853051/13931854/82177e40-ef62-11e5-8fc7-ae56f378fe94.png">
<img width="956" alt="screen shot 2016-03-21 at 12 43 00" src="https://cloud.githubusercontent.com/assets/853051/13931856/8231405a-ef62-11e5-9d42-b91d49cf5b23.png">

**Comment by thisisaaronland** [comment]
```
wc -l qs-points-20160325*.csv
  234126 qs-points-20160325-add.csv
  109470 qs-points-20160325-missing-iso.csv
   14854 qs-points-20160325-skip.csv
    6589 qs-points-20160325-suspect-qs.csv
```

Where missing ISO means there was no match for the ISO country code in the row (in `qs-points-review-20160305-no-wof.csv`) that mapped to the list of ISO country codes derived from `qs_gazetteer_import_strategy.txt`

**Comment by thisisaaronland** [comment]
Where the placetype is listed as `UNKNOWN`.

```
grep UNKNOWN ./qs-points-20160325-add.csv > ./qs-points-20160325-add-unknown.csv
wc -l ./qs-points-20160325-add-unknown.csv
54312
```

```
grep -v UNKNOWN ./qs-points-20160325-add.csv > ./qs-points-20160325-add-known.csv
wc -l ./qs-points-20160325-add-known.csv
179814
```

**Comment by thisisaaronland** [comment]
```
python ./placetypes.py ./qs-points-20160325-add-known.csv
{'Town': 100506, 'Suburb': 14058, 'State': 516, 'LocalAdmin': 54397, 'County': 10336}
```

**Comment by thisisaaronland** [comment]
`qs-points-20160325-missing-iso.csv` can be reverse geocoded against the WOF countries set, easily enough.

**Comment by thisisaaronland** [comment]
`qs-points-20160325-missing-iso.csv` filtered for placetypes marked `UNKNOWN` and reverse geocoded:

```
wc -l qs-points-20160325*-2.csv
  41593 qs-points-20160325-add-2.csv
  21164 qs-points-20160325-missing-iso-2.csv
  12961 qs-points-20160325-skip-2.csv
   1240 qs-points-20160325-suspect-qs-2.csv
  76958 total
```

**Comment by thisisaaronland** [comment]
Ugh. Actually: 

```
wc -l qs-points-20160325-*.csv
   36159 qs-points-20160325-add.csv
   73312 qs-points-20160325-missing-iso.csv
  234126 qs-points-20160325-skip.csv
    6589 qs-points-20160325-suspect-open.csv
   14854 qs-points-20160325-suspect-qs.csv
  365040 total
```

I confused `0` with `1`. This is why we do dry-runs..

Filtered for known placetypes:

```
wc -l qs-points-20160325-add-known.csv
12937 qs-points-20160325-add-known.csv
```

**Comment by thisisaaronland** [comment]
Again, things without a country code filtered for not-UNKNOWN placetypes and reverse geocoded:

```
wc -l qs-points-20160325-*2.csv
   4484 qs-points-20160325-add-2.csv
   3755 qs-points-20160325-missing-iso-2.csv
  41585 qs-points-20160325-skip-2.csv
   1240 qs-points-20160325-suspect-open-2.csv
  12959 qs-points-20160325-suspect-qs-2.csv
  64023 total
```

**Comment by thisisaaronland** [comment]
```
python pt.py qs-points-20160325-add-known.csv qs-points-20160325-add-2.csv
{'Town': 11042, 'Suburb': 543, 'State': 45, 'LocalAdmin': 236, 'County': 1070}
```

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/whosonfirst-data/commit/36a13f3acfa1ca0c8f0fd7b312b30ef6336322e3

See also: whosonfirst-toolbox/scripts/issue-222-*
