### ISSUE TITLE
Chelsea, NY shouldn't be parented by localadmin Brooklyn

### ISSUE THREAD

**Issue by dianashk** [whosonfirst/whosonfirst-data#226]
https://whosonfirst.mapzen.com/spelunker/id/85810589/

### Hierarchy
>the county of Kings
>**the localadmin of Brooklyn** :construction: 
>the locality of New York
>the neighbourhood of Chelsea
>the continent of North America
>the country of United States
>the region of New York

**Comment by dianashk** [comment]
Same goes for Soho: 

https://whosonfirst.mapzen.com/spelunker/id/85865687/

###Hierarchy
>the county of Kings
>**the localadmin of Brooklyn** :construction: 
>the locality of New York
>the neighbourhood of Soho
>the continent of North America
>the country of United States
>the region of New York

**Comment by dianashk** [comment]
aaaand Ridgewood, NY

https://whosonfirst.mapzen.com/spelunker/id/85844581/

### Hierarchy
>the county of Kings
>the localadmin of Brooklyn
>the locality of New York
>the neighbourhood of Ridgewood
>the continent of North America
>the country of United States
>the region of New York

**Comment by trescube** [comment]
All of New York City (the locality) is a child of localadmin for Brooklyn:

https://whosonfirst.mapzen.com/spelunker/id/85977539/

**Comment by trescube** [comment]
I've attached a patch that fixes all 86 Manhattan neighbourhoods that were assigned to Brooklyn/Kings County (zipped to appease the github gods).
  
[0001-updated-these-Manhattan-neighbourhoods-to-point-to-M.patch.zip](https://github.com/whosonfirst/whosonfirst-data/files/177155/0001-updated-these-Manhattan-neighbourhoods-to-point-to-M.patch.zip)
