### ISSUE TITLE
Name for `The Hague` looks to be corrupted

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst/whosonfirst-data#227]
https://whosonfirst.mapzen.com/spelunker/id/101752763/

From the concordances this is clearly the record for The Hague, but the title is quite wrong. Parent regions look to possibly have similar name issues.

**Comment by nvkelso** [comment]
I agree both WOF records should be changed to read `Den Haag` (preferred Dutch name). The current WOF name is from the official gov't data (and is not a regression over Quattroshapes), and relates to the official / historical name for the city and it's surrounding region.

Same thing can happen in USA. Here's [Ventura](https://whosonfirst.mapzen.com/spelunker/id/85923223/) which is coming thru as `San Buenaventura (Ventura)` but should just read `Ventura`. 

From the WOF names section (localized names from WOE GeoPlanet):

```
dut_x_preferred	Den Haag
eng_x_preferred	The Hague
```

**Comment by nvkelso** [comment]
Interesting interface to compare basic stats about two places, especially for reduplication:

* http://morelesscompare.com/cities-in-netherlands/amsterdam-vs-s-gravenhage-den-haag/

<img width="1200" alt="screen shot 2016-03-15 at 12 18 09" src="https://cloud.githubusercontent.com/assets/853051/13790959/0f68dfc4-eaa8-11e5-8b18-7b8dac2791bb.png">

**Comment by thisisaaronland** [comment]
Updated `wof:name` to be "The Hague" because of the rule about `wof:name` and the eventual default `wof:label` being 7-bit ASCII transliterated English. Variants (inclusive of non-English names) are kept in the `name:*` fields.
