### ISSUE TITLE
no wof:name, instead zs:name?

### ISSUE THREAD

**Issue by peterneubauer** [whosonfirst/whosonfirst-data#230]
Hi there,

https://github.com/whosonfirst/whosonfirst-data/blob/master/data/420/558/257/420558257.geojson

is not containing a wof:name, only zs:name. Is that ok and intended?

**Comment by nvkelso** [comment]
I see a:
"wof:name":"West Torresdale",

What do you see?

**Comment by thisisaaronland** [comment]
@nvkelso - that might be because I fixed things between then and now and forgot to update this ticket...

**Comment by peterneubauer** [comment]
After a git pull the `wof:name` is there, but now found another one, https://raw.githubusercontent.com/whosonfirst/whosonfirst-data/master/data/420/558/259/420558259.geojson ?
