### ISSUE TITLE
Update city of "Gurgaon" to "Gurugram"

### ISSUE THREAD

**Issue by tallytalwar** [whosonfirst/whosonfirst-data#245]
News Update: http://www.thehindu.com/news/national/gurgaon-renamed-as-gurugram/article8467206.ece

WoF Id: https://whosonfirst.mapzen.com/spelunker/id/102030161
Decendants: https://whosonfirst.mapzen.com/spelunker/id/102030161/descendants/#12/28.4710/77.0464

**Comment by thisisaaronland** [comment]
SUPERSEDE ALL THE THINGS.

Write down all the steps, particularly which services need to be updated and in what order.

**Comment by nvkelso** [comment]
@thisisaaronland I think this is just a name change on the `161` record. Easy for @stepps00 to do?

**Comment by nvkelso** [comment]
PR looks good. But please add this as an example in a "supersedes / superseded by" WIKI doc.
