### ISSUE TITLE
Clean up Census (balance) artifacts – one feature or many?

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#251]
Picking up where #193 leaves off...

```
@martinburch from the Wall Street Journal flagged an issue (pelias/pelias#237) with several 
locality names in WoF/Quattroshapes where the name of the city ends in (balance):

In both OSM and Quattroshapes, some localities end in "balance" as in Athens-Clarke County 
Unified Government (balance)
https://search.mapzen.com/v1/reverse?api_key=xxxxxxxxx&point.lat=33.94806&point.lon=-83.3275&sources=osm

(Example link]

This looks like an artifact of Census-derived data. There are only a handful of these in the 
U.S. Can this be cleaned up somehow?
```

**Comment by nvkelso** [comment]
On the surface, the many parts of a `locality` should just be one feature. But the downside is would be be able to say which **part** of the `locality` is a child of which `county`?

**Comment by martinburch** [comment]
## Indianapolis
I think there is a missing locality entity, `Indianapolis`, which could be a synonym for `Marion` county, simplistically, or could include all Marion's locality children, except the [excluded cities](https://en.wikipedia.org/wiki/Unigov#Excluded_cities_and_town) of 85942579 Beech Grove, 85942567 Lawrence, 85942559 Southport and 85942555 Speedway.

The locality 85942569 Indianapolis city (balance) only exists in Census-land. It could be removed or renamed `Indianapolis`

https://whosonfirst.mapzen.com/spelunker/id/102087201/descendants/?&placetype=locality#10/39.7802/-86.1458

## Athens
For `Athens-Clarke County unified government (balance)`, this shape is synonymous with the city of `Athens`, and that's the most common vernacular name. The hole of 85936181 Winterville is not part of Athens.

https://whosonfirst.mapzen.com/spelunker/id/102081713/descendants/?&placetype=locality#14/33.9587/-83.3689

## Other ` (balance)`
Looking at these two examples, it seems the easiest thing to do would be to rename the ` (balance)` entries to their city names but there might be other case-by-case solutions that more accurately reflect local governance hierarchies.

**Comment by nvkelso** [comment]
For Indianapolis, it's current localadmin is `Center`!?

**Comment by nvkelso** [comment]
@martinburch Good point about Indianapolis "core" missing entirely! That's kinda odd, suggest a reimport from US Census / Quattroshapes for this feature is in order, or take the county boundary, add the balance to it, subtract the independent cities to get the new polygon geom.

See also:

* https://whosonfirst.mapzen.com/spelunker/id/102087201/descendants/?&placetype=locality#10/39.7802/-86.1458

**Comment by martinburch** [comment]
Is `Center` what happened to the localadmin that shoulda been named `Indianapolis`? I'm not familiar with how localadmin fits into the hierarchy.

The Indianapolis core (center of the city) does seem to be included in the `(balance)` shape.

**Comment by nvkelso** [comment]
From @trescube's comment a few days ago in https://github.com/whosonfirst/whosonfirst-data/pull/260#issuecomment-215107785:

```
There are 7 more localities containing the word balance:

101723183|Nashville-Davidson metropolitan government (balance)
85930905|Milford city (balance)
85947523|Louisville/Jefferson County metro government (balance)
85972699|Butte-Silver Bow (balance)
85936177|Athens-Clarke County unified government (balance)
85945489|Greeley County unified government (balance)
85936989|Augusta-Richmond County consolidated government (balance)
```

**Comment by nvkelso** [comment]
After the related PRs are all merged (see list above), this can be closed.

**Comment by nvkelso** [comment]
Err, @stepps00 Do we need to do anything for `85972699` **Butte-Silver Bow** and for **Jacksonville** in Florida to match up with the pending PRs?

See: 

* https://en.wikipedia.org/wiki/Butte,_Montana
* https://en.wikipedia.org/wiki/Jacksonville,_Florida

**Comment by stepps00** [comment]
51d0b13 - Takes care of `Butte-Silver Bow (balance)`. 

[Jacksonville](https://whosonfirst.mapzen.com/spelunker/id/85932547/#9/30.3456/-81.6847) looks correct. Is this the correct record to edit?

**Comment by nvkelso** [comment]
Jacksonville looks good as-is.

**Comment by stepps00** [comment]
Closing - all branches merged to master.
