### ISSUE TITLE
Birmingham/Wolverhampton/Walsall/Dudley

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-data#253]
https://whosonfirst.mapzen.com/spelunker/id/101750467/#10/52.4957/-1.8949

place name seems to contain 4 different place names:
> Birmingham/Wolverhampton/Walsall/Dudley

**Comment by stepps00** [comment]
Changed `wof:name` to Birmingham.. geometry only covers the locality of Birmingham.

**Comment by nvkelso** [comment]
@stepps00 Is there an open PR for this, or did it get merged to master already?
