### ISSUE TITLE
"Okanagan 1" - naming issue inherited from Quattroshapes?

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst/whosonfirst-data#256]
https://en.wikipedia.org/wiki/Okanagan

https://whosonfirst.mapzen.com/spelunker/id/101748047/

This appears to be a naming issue that followed us from Quattroshapes. Should we drop the 1, assuming this place is the place Wikipedia calles Okanagan?

**Comment by stepps00** [comment]
Closing, as 2a480dd was merged to Master.
