### ISSUE TITLE
Tuvalu geometry is offset

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst/whosonfirst-data#257]
![whosonfirst-spelunker-1461606765717](https://cloud.githubusercontent.com/assets/111716/14793443/3b91f4a4-0aed-11e6-9bbd-c5ddaf89cde5.png)

See https://whosonfirst.mapzen.com/spelunker/id/85632607/#11/-8.5403/179.1499 as well.

It looks like the geometry is offset enough that it misses the island entirely. This makes [pelias sad](http://pelias.github.io/compare/#/v1/search%3Flayers=coarse&size=1&text=Funafuti,%20Tuvalu)

**Comment by stepps00** [comment]
* Moved geometries, Funafuti now covered by main island.
* New issue opened to clean up various outlying islands: https://github.com/whosonfirst/whosonfirst-data/issues/272
