### ISSUE TITLE
Durrington, England, UK

### ISSUE THREAD

**Issue by dianashk** [whosonfirst/whosonfirst-data#270]
Durrington, a localadmin in UK, has a CP on the end of the name. User from EM identified this issue.
Are there other names with CP?

https://whosonfirst.mapzen.com/spelunker/id/404454187/#13/51.1976/-1.8079

**Comment by nvkelso** [comment]
I think the CP refers to `civil parish`. The ` Cp` bit should come off. But looks to be a widespread problem affecting ~10,000 records. 

Suggest we remove ` Cp` from the name, but adding ` civil parish` to a search name (this seems the same as the request to add ` parish` to Louisiana county features).

* https://whosonfirst.mapzen.com/spelunker/search/?q=+Cp&placetype=localadmin#6/52.395/-1.479
* https://en.wikipedia.org/wiki/Civil_parishes_in_England
* https://en.wikipedia.org/wiki/Durrington,_Wiltshire

**Comment by stepps00** [comment]
For 10,508 records:

* Exported all `Civil Parish and Community` records in GB
* Queried to only include records with string of ` CP` in `wof:name` field
* Removed the string `" CP"` from `wof:name:` field
* Created new field for search (`wof:label`), equal to (new `wof:name` + ` Civil Parish`)
* Hooks updated `wof:lastmodified`

Imported using `Issue270` script
