### ISSUE TITLE
WOF doesn't have an entry for Mexico City

### ISSUE THREAD

**Issue by louh** [whosonfirst/whosonfirst-data#293]
e.g.
https://whosonfirst.mapzen.com/spelunker/search/?q=mexico+city#4/31.04/-103.34

even Ciudad de México doesn't work but it finds a bunch of places around it
https://whosonfirst.mapzen.com/spelunker/search/?q=Ciudad+de+M%C3%A9xico#5/25.640/-106.500

is it supposed to be more-or-less this? https://whosonfirst.mapzen.com/spelunker/id/85686515/#9/19.4252/-99.1159

**Comment by stepps00** [comment]
Hmm.. A `locality` record for Mexico City should be parented by the [Distrito Federal](https://whosonfirst.mapzen.com/spelunker/id/85686515/#9/19.4252/-99.1159) `region` record, but we don't have that WOF record. The Distrito Federal is comprised _mostly_ of Mexico City, but it also includes land south of Mexico City. In the screenshot below, Mexico City is represented in light green, Distrito Federal is represented in dark green.

A new record should be created for Mexico City as a `locality`.


<img width="578" alt="screen shot 2016-05-20 at 10 14 06 am" src="https://cloud.githubusercontent.com/assets/18567700/15435863/a359d4fa-1e73-11e6-81c4-040e0c08089d.png">

**Comment by stepps00** [comment]
The above proposal is incorrect - earlier this year, the Mexican government officially [changed the name of the Distrito Federal to "Ciudad de México."](http://www.theguardian.com/world/2016/jan/29/mexico-city-name-change-federal-district-df) In turn, "Ciudad de México" now encompasses the sixteen  [municipalities](https://whosonfirst.mapzen.com/spelunker/id/85686515/descendants/?&placetype=county#10/19.3219/-99.1159) of Distrito Federal.

**Comment by louh** [comment]
You learn something new every day!
