### ISSUE TITLE
Add empires

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#3]
The following "empires" are tracked in Natural Earth" as "Sovereignty" at the admin-0 level:

1. Australia
1. China
1. Denmark
1. Finland
1. France
1. Israel
1. Netherlands
1. New Zealand
1. United Kingdom
1. United States of America

**Comment by thisisaaronland** [comment]
cat /usr/local/mapzen/whosonfirst-data/meta/wof-empire-latest.csv
bbox,fullname,geomhash,id,iso,lastmodified,name,parent_id,path,source,superseded_by,supersedes
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253055,XY,1440029558,United Kingdom,0,136/253/055/136253055.geojson,,,
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253051,XY,1440029516,Netherlands,0,136/253/051/136253051.geojson,,,
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253045,XY,1440029481,Denmark,0,136/253/045/136253045.geojson,,,
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253039,XY,1440029463,Australia,0,136/253/039/136253039.geojson,,,
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253053,XY,1440029524,New Zealand,0,136/253/053/136253053.geojson,,,
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253057,XY,1440029565,United States of America,0,136/253/057/136253057.geojson,,,
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253049,XY,1440029504,Israel,0,136/253/049/136253049.geojson,,,
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253047,XY,1440029490,Finland,0,136/253/047/136253047.geojson,,,
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253037,XY,1440029215,France,0,136/253/037/136253037.geojson,,,
"0.0,0.0,0.0,0.0",,e898cfa3959981262f8d75c8fecdb4cb,136253041,XY,1440029471,China,0,136/253/041/136253041.geojson,,,

ISO country code assigned to XY per this:

https://github.com/whosonfirst/whosonfirst-placetypes#xy
