### ISSUE TITLE
Ukranian counties in need of merging?

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-data#306]
In the process of doing a dry-run to fix issue #244 I noticed that some WOF records appear to have the same `qs:a2_lc` property:

```
python ./wtf-ua.py qs_adm2.geojson
WTF count for UA6524700000 is 2
WTF count for UA4825100000 is 2
WTF count for UA6524700000 is 2
WTF count for UA4825100000 is 2
```

Or: https://whosonfirst.mapzen.com/spelunker/search/?q=UA6524700000

At a glance these appear to be non-contiguous landmasses that were imported as separate records?

**Comment by stepps00** [comment]
Looks like that's the case. I will combine the geometries for each pair of records that share `qs:a2_lc` properties, update one record, and deprecate the unused record.

**Comment by thisisaaronland** [comment]
Cool - the unused record should also be superseded.
