### ISSUE TITLE
Some Kansas townships have names that are simply numbers

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst/whosonfirst-data#313]
_This issue was originally reported by @martinburch in pelias/pelias#238_

Kansas has townships that apparently have no name, just a number. In WOF, they show up simply as "5" or "6". @martinburch suggests "Township 5" or "Township 6" would be better, more official names.

See https://whosonfirst.mapzen.com/spelunker/search/?q=5&placetype=localadmin&iso=us&region_id=85688555#7/38.383/-100.929 and https://whosonfirst.mapzen.com/spelunker/search/?q=6&placetype=localadmin&iso=us&region_id=85688555#7/38.375/-94.915 for examples.

**Comment by nvkelso** [comment]
Sounds good.

**Comment by stepps00** [comment]
https://en.wikipedia.org/wiki/List_of_townships_in_Kansas
