### ISSUE TITLE
Add new mz:hierarchy_label property

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#320]
Pelias would like to know when to include (or not include) the neighbourhood name in the place label (e.g., `273 29th St, Noe Valley, San Francisco, California, United States` versus leaving "Noe Valley" out).

There are a couple rough proxies for this now:

- `mz:is_funky` - never include it in the label as something is very wrong with the feature.
- `mz:tier_locality` - tiers 7 and 6 are probably always label-able. Where tiers 1 and 2 are probably never. 
- `mz:min_zoom` - generally things with a smaller min zoom value show up earlier on the map, and can be included in the label. But this is not 100% curated yet, and some labels in big cities show up late because of display fitting / label collisions. 

We should:

0. populate a new `mz:hierarchy_label` property that is a boolean (like `is_funky`) that probably defaults to true unless set to 0 manually. 

1. This issue should add this new property to all `macrohood`, `neighbourhood`, and `microhood` features in WOF, set to `1`. 

2. Then in another pass for the same PR we should exclude tier 1, 2, and 3 locality neighbourhoods (set the value to `0`). 

3. Then I'll need to look over Nat's research to determine if some of the tier 4 and 5 locality neighbourhoods should also be excluded (my guess is a lot of them should be set to `0`).

**Comment by nvkelso** [comment]
Related: fixing up Iowa tier_locality values: https://github.com/whosonfirst/whosonfirst-data/issues/322.

**Comment by nvkelso** [comment]
Looking at https://github.com/pelias/pelias/issues/292, it seems like we should generate this (defaulted to `1` as true) for all administrative placetypes so it could optionally be turned off.

**Comment by thisisaaronland** [comment]
This is being processed as part of issue #338

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/whosonfirst-data/commit/cd3e108e762da2632c531d7ed1d74637922e90f2

**Comment by nvkelso** [comment]
> 1. This issue should add this new property to all macrohood, neighbourhood, and microhood features in WOF, set to 1.

Done in https://github.com/whosonfirst/whosonfirst-data/commit/cd3e108e762da2632c531d7ed1d74637922e90f2. 

> 2. populate a new mz:hierarchy_label property that is a boolean (like is_funky) that probably defaults to true unless set to 0 manually.

Done in https://github.com/whosonfirst/whosonfirst-data/commit/cd3e108e762da2632c531d7ed1d74637922e90f2. 

> 3. Then in another pass for the same PR we should exclude tier 1, 2, and 3 locality neighbourhoods (set the value to 0).

@thisisaaronland Was this done in the commit, or should I file a new issue? I suspect yes but Github search isn't being useful to me to confirm.

4. Then I'll need to look over Nat's research to determine if some of the tier 4 and 5 locality neighbourhoods should also be excluded (my guess is a lot of them should be set to 0).

This definitely should be a new issue: https://github.com/whosonfirst/whosonfirst-data/issues/341.

**Comment by thisisaaronland** [comment]
No. Everything was blanket set to `1` because there was a comment to that effect (somewhere... ?) at least in the short term.

If we need to backfill specific records with specific properties would you open a new ticket please?

**Comment by nvkelso** [comment]
Filed: https://github.com/whosonfirst/whosonfirst-data/issues/342.

**Comment by nvkelso** [comment]
Added details for Pelias adoption in https://github.com/pelias/wof-pip-service/issues/40.
