### ISSUE TITLE
geojson file not present in csv

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-data#325]
re: https://whosonfirst.mapzen.com/spelunker/id/420784293

this neighbourhood record is not present in the meta files.
Is there a reason some are present and some not, or maybe the meta files just need an update?

```bash
$ grep 420784293 meta/wof-neighbourhood-latest.csv 
$ echo $?
1

$ grep 420784293 meta/*
$ echo $?
1
```

```
$ git log -1
commit e434097d588cecc45f9868056dcff2aa7c9b1c9e
Merge: 59b68ff 3acb682
Author: Stephen Epps <stephen.epps@mapzen.com>
Date:   Fri Jun 3 12:40:25 2016 -0700

    Merge pull request #317 from whosonfirst/stepps00-SFaltgeom
    
    created alt-geom for SF and updated SF record with new alt src
```

**Comment by thisisaaronland** [comment]
Huh, I will take a look shortly.

**Comment by missinglink** [comment]
agh, it seems this Feature is a Point, not a Polygon, that's probably why..

**Comment by missinglink** [comment]
I can probably close this, I'm assuming it's only Polygons in the csv files correct?

**Comment by thisisaaronland** [comment]
In the meta files? No, that would be a bug.

**Comment by thisisaaronland** [comment]
```
grep 420784293 meta/wof-neighbourhood-latest.csv 
"13.3908798012,52.5158590675,13.3908798012,52.5158590675",uuuu,85633111,,baf7d2836cbae89d7994829c97472a83,,73b753aaffb4677b98d5f7f5643c06ad,52.515859,13.39088,420784293,uuuu,,,1458871921,52.515859,13.39088,101748799,MItte,101748799,420/784/293/420784293.geojson,neighbourhood,85682499,,,,
```

Bundles will still need to regenerated but that is a separate issue.

**Comment by thisisaaronland** [comment]
Re-opening because merge hoohah and diff nonsense being included in the CSV files. Re-building them now...
