### ISSUE TITLE
Import admin-1-regions from Quattroshapes as new region-group placetype

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#34]
We're missing several important country subdivisions between WOF country and WOF region. These features are in Quattroshapes as admin-1-regions, let's import them and adjust the hierarchy to include an common optional region-group placetype.

**Comment by nvkelso** [comment]
Super regions?

**Comment by nvkelso** [comment]
Related: 

* https://github.com/whosonfirst/whosonfirst-data/issues/112
* https://github.com/whosonfirst/whosonfirst-data/issues/111

**Comment by stepps00** [comment]
These were imported, see: https://whosonfirst.mapzen.com/spelunker/placetypes/macroregion/#3/54.58/-7.91
