### ISSUE TITLE
Add populations from wikidata

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#343]
Looking at Wikipedia and the Wikidata project, we can pull population numbers for many places. Please attach a CSV with the WOF:id and the wikidata population values for import.

**Comment by okavvada** [comment]
Find attached a CSV file with WOF concordances with Wikipedia properties. Specifically, the properties involve population, area, elevation from the sea level, latitude, longitude, wordcount and wikidata ID.
It consists of 155k where:
5,600 of which have `population` values
10,000 of which have `elevation` values
26,000 of which have `lat` & `lon` values
155 k have `wordcount`
154 k have `wd:id`

[final_titles_ids_all_clean_population.zip](https://github.com/whosonfirst/whosonfirst-data/files/338214/final_titles_ids_all_clean_population.zip)

**Comment by okavvada** [comment]
Over to @thisisaaronland
