### ISSUE TITLE
Add wikidata concordances

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#344]
Looking at Wikipedia and the Wikidata project, we can pull population numbers for many places. Please attach a CSV with the WOF:id and the wikidata ID

**Comment by okavvada** [comment]
Attaching a CSV with wikidata ID concordances. The csv consists of the `wof:id` column and the `wd:id` column. 

[final_wd_ids_clean.zip](https://github.com/whosonfirst/whosonfirst-data/files/338150/final_wd_ids_clean.zip)

**Comment by okavvada** [comment]
Over to @thisisaaronland
