### ISSUE TITLE
Add multiple language names from Wikipedia

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#346]
Looking at Wikipedia and the Wikidata project, we can pull in more localized names. Please attach a data file with the WOF:id and the different localized names for import.

**Comment by okavvada** [comment]
Attaching a JSON file with all the localized names pulled from the Wikipedia API. It is in the form of a dictionary where the keys are the `wof:id` and the values are the corresponding localized languages of each key. On average each key is translated in 15 localized languages. The total number of `wof:id` values with localized languages identified is about 135k, ending up to a sum of about 2 million language inputs.

https://raw.githubusercontent.com/mapzen-data/wikipedia-notebooks/master/OUTPUTS_languages/languages_dict_clean_wof.json

**Comment by nvkelso** [comment]
Over to @thisisaaronland

**Comment by thisisaaronland** [comment]
Dry-run yields this:

```
python ./names.py 20160628-languages_dict_clean_wof.json
1944195 names
276 languages
135673 records
```

**Comment by thisisaaronland** [comment]
Okay, this needs a little more work. Specifically: Names in WOF should not contain hierarchical information. For example `Potsdam` and not `Potsdam, Ohio` or `Potsdam (Ohio)`. See below.

Those longer names would actually be really really useful for a `label:*` fields in WOF so don't get rid of them but can you try teasing out just the place name in to a separate field?

```
+    "name:hat_x_preferred":[
+        "Potsdam, Ohio"
+    ],
+    "name:hbs_x_preferred":[
+        "Potsdam, Ohio"
+    ],
+    "name:mlg_x_preferred":[
+        "Potsdam, Ohio"
+    ],
+    "name:nld_x_preferred":[
+        "Potsdam (Ohio)"
+    ],
+    "name:por_x_preferred":[
+        "Potsdam (Ohio)"
+    ],
+    "name:spa_x_preferred":[
+        "Potsdam (Ohio)"
+    ],
+    "name:srp_x_preferred":[
+        "\u041f\u043e\u0442\u0441\u0434\u0430\u043c (\u041e\u0445\u0430\u0458\u043e)"
+    ],
+    "name:vie_x_preferred":[
+        "Potsdam, Ohio"
+    ],
```

**Comment by okavvada** [comment]
I am attaching a new JSON file which has the clean names (without the hierarchy information). We can keep the old JSON for the labeling and this one for the actual names. It is in the form of a dictionary where the keys are the `wof:id` and the values are the corresponding localized languages of each key.

[languages_wof_dict_clean_values.zip](https://github.com/whosonfirst/whosonfirst-data/files/339812/languages_wof_dict_clean_values.zip)

**Comment by okavvada** [comment]
Over to @thisisaaronland

**Comment by thisisaaronland** [comment]
w00t!
