### ISSUE TITLE
Add sample custom label bounding boxes to SF and Tokyo

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#361]
Picking up from @orangejulius suggestion in https://github.com/pelias/pelias/issues/370, let's add samples in WOF for San Francisco locality and Tokyo locality & maybe region, too, setting a custom "label bounding box" that is tight on the main land mass (e.g.: excluding the [Farallon Islands](https://en.wikipedia.org/wiki/Farallon_Islands) for SF).

**Comment by stepps00** [comment]
@nvkelso I'm envisioning each sample case's `geom` section would look something like the following:

  `"geom:area":0.061408,`
   `"geom:bbox":"-123.173825,37.63983,-122.28178,37.929824",`
   `"geom:bbox_label":" -122.51489,37.70808,-122.35698,37.81157,`
   `"geom:latitude":37.759715,`
   `"geom:longitude":-122.693976,`

Would this be Pelias-readable or should we replace the `geom:bbox` completely?

**Comment by nvkelso** [comment]
I think it should go in the existing `lbl` section as a new `bbox`
property. More like:

```
"lbl:latitude":37.778008,
"lbl:longitude":-122.431272,
"lbl:bbox":"-123.173825,37.63983,-122.28178,37.929824”,
```
