### ISSUE TITLE
~800k points missing administrative hierarchy

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-data#379]
~800k points are missing any administrative hierarchy data. These do not fall in any of the Who's on First polygons for `country`, `macroregion`, `region`, `macrocounty`, `county`, `locality`, `localadmin`, or `neighbourhood`.

The majority of these are likely country polygons that are not sufficiently inclusive.

See [Pelias Issue 276](https://github.com/pelias/pelias/issues/276) for more information.

**Comment by nvkelso** [comment]
This is probably more a function of knowing what `alt` geometry in Who's In First to use (the default geometry in the WOF record is often not the most details for this).

Closing this issue now in favor of https://github.com/whosonfirst/whosonfirst-data/issues/367 which tracks indicating a reverse geocoding geometry for records (mostly country needing a backfill).

If it's still a problem after that, reopen this issue or file another one.
