### ISSUE TITLE
Investigate and fix Puerto Rico

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst/whosonfirst-data#39]
WOF may be missing all of the municipalities (or maybe they are not being categorized as regions).

For reference, Statoids lists 78 municipalities as the primary subdivision for Puerto Rico.

**Comment by nvkelso** [comment]
Hoping US Census comes through here...

**Comment by nvkelso** [comment]
These are actually in WOF now as admin-2 "county" features, so we might already be good. Except I only see 77 (one shy of 78).

**Comment by stepps00** [comment]
The discrepancy in County records for Puerto Rico is coming from the record of Mayagüez. The centroid is outside of the Puerto Rico country region, hence no heirarchy. Will file PR to merge.

https://whosonfirst.mapzen.com/spelunker/id/102080311/#10/18.2196/-67.5089
