### ISSUE TITLE
Link up countries, dependencies, disputes to empires

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#4]
A couple dozen countries, dependencies, & disputed areas should be linked up to parent empires.

Document research here and apply data changes.

**Comment by stepps00** [comment]
`wof:id`of each Empire record:

wof:name | wof:id
---- | ----
France | 136253037
Australia | 136253039
China | 136253041
Denmark | 136253045
Finland | 136253047
Israel | 136253049
Netherlands | 136253051
New Zealand | 136253053
United Kingdom |136253055
United States of America	 | 136253057

**Comment by nvkelso** [comment]
> For the single case in Kazakhstan and the single case in Cuba - should we create new empire record?

Answering this in Github now (answered in person last week)...

The list above is an old copy paste. I think the live data has been updated so the Kazakhstan case is now Russia, and the Cuba case is now USA.
