### ISSUE TITLE
Coratia regions don't need the suffix in the default name

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#54]
parent_name	name	parent_id	iso	id
Croatia	Bjelovarsko-bilogorska županija	85633229	HR	85684753
Croatia	Brodsko-posavska županija	85633229	HR	85684749
Croatia	Disputed areas of Croatia	85633229	HR	85684741
Croatia	Dubrovacko-neretvanska županija	85633229	HR	85684775
Croatia	Grad Zagreb	85633229	HR	85684811
Croatia	Inland waters of Croatia	85633229	HR	85684785
Croatia	Istarska županija	85633229	HR	85684829
Croatia	Karlovacka županija	85633229	HR	85684819
Croatia	Koprivnicko-križevacka županija	85633229	HR	85684799
Croatia	Krapinsko-zagorska županija	85633229	HR	85684813
Croatia	Licko-senjska županija	85633229	HR	85684737
Croatia	Medimurska županija	85633229	HR	85684823
Croatia	Osjecko-baranjska županija	85633229	HR	85684805
Croatia	Požeško-slavonska županija	85633229	HR	85684763
Croatia	Primorsko-goranska županija	85633229	HR	85684789
Croatia	Šibensko-kninska županija	85633229	HR	85684755
Croatia	Sisacko-moslavacka županija	85633229	HR	85684769
Croatia	Splitsko-dalmatinska županija	85633229	HR	85684781
Croatia	Varaždinska županija	85633229	HR	85684835
Croatia	Viroviticko-podravska županija	85633229	HR	85684793
Croatia	Vukovarsko-srijemska županija	85633229	HR	85684733
Croatia	Zadarska županija	85633229	HR	85684807
Croatia	Zagrebacka županija	85633229	HR	85684765

**Comment by stepps00** [comment]
[Regions in Croatia](https://whosonfirst.mapzen.com/spelunker/id/85633229/descendants/?&placetype=region#6/44.676/15.282) were edited in the commits above through a bulk update of new `wof:name` fields. The suffix of `županija` should now be removed from these records.

Closing issue.
