### ISSUE TITLE
Latvia regions don't need the suffix in the default name

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#55]
parent_name	name	parent_id	iso	id
Latvia	Adažu novads	85633279	LV	85686113
Latvia	Aglonas novads	85633279	LV	85685855
Latvia	Aizkraukles novads	85633279	LV	85685965
Latvia	Aizputes novads	85633279	LV	85685867
Latvia	Aknistes novads	85633279	LV	85685819
Latvia	Alojas novads	85633279	LV	85686293
Latvia	Alsungas novads	85633279	LV	85685961
Latvia	Aluksnes novads	85633279	LV	85686279
Latvia	Amatas novads	85633279	LV	85686173
Latvia	Apes novads	85633279	LV	85686269
Latvia	Auces novads	85633279	LV	85685839
Latvia	Babites novads	85633279	LV	85686027
Latvia	Baldones novads	85633279	LV	85685957
Latvia	Baltinavas novads	85633279	LV	85686179
Latvia	Balvu novads	85633279	LV	85686235
Latvia	Bauskas novads	85633279	LV	85685851
Latvia	Beverinas novads	85633279	LV	85686261
Latvia	Brocenu novads	85633279	LV	85685885
Latvia	Burtnieku novads	85633279	LV	85686283
Latvia	Carnikavas novads	85633279	LV	85686107
Latvia	Cesu novads	85633279	LV	85686193
Latvia	Cesvaines novads	85633279	LV	85686151
Latvia	Ciblas novads	85633279	LV	85686089
Latvia	Dagdas novads	85633279	LV	85685893
Latvia	Daugavpils	85633279	LV	85685795
Latvia	Daugavpils novads	85633279	LV	85685825
Latvia	Dobeles novads	85633279	LV	85685925
Latvia	Dundagas novads	85633279	LV	85686221
Latvia	Durbes novads	85633279	LV	85685829
Latvia	Engures novads	85633279	LV	85686103
Latvia	Erglu novads	85633279	LV	85686085
Latvia	Garkalnes novads	85633279	LV	85686073
Latvia	Grobinas novads	85633279	LV	85685811
Latvia	Gulbenes novads	85633279	LV	85686241
Latvia	Iecavas novads	85633279	LV	85685905
Latvia	Ikškiles novads	85633279	LV	85686017
Latvia	Ilukstes novads	85633279	LV	85685815
Latvia	Incukalna novads	85633279	LV	85686117
Latvia	Jaunjelgavas novads	85633279	LV	85685947
Latvia	Jaunpiepalgas novads	85633279	LV	85686175
Latvia	Jaunpils novads	85633279	LV	85685921
Latvia	Jekabpils	85633279	LV	85685911
Latvia	Jekabpils novads	85633279	LV	85685889
Latvia	Jelgava	85633279	LV	85685881
Latvia	Jelgavas novads	85633279	LV	85685971
Latvia	Jurmala	85633279	LV	85686031
Latvia	Kandavas novads	85633279	LV	85686061
Latvia	Karsavas novads	85633279	LV	85686139
Latvia	Keguma novads	85633279	LV	85686011
Latvia	Kekavas novads	85633279	LV	85685999
Latvia	Kocenu novads	85633279	LV	85686257
Latvia	Kokneses novads	85633279	LV	85686023
Latvia	Kraslavas novads	85633279	LV	85685833
Latvia	Krimuldas novads	85633279	LV	85686203
Latvia	Krustpils novads	85633279	LV	85685991
Latvia	Kuldigas novads	85633279	LV	85686043
Latvia	Lielvardes novads	85633279	LV	85685995
Latvia	Liepaja	85633279	LV	85685799
Latvia	Ligatnes novads	85633279	LV	85686153
Latvia	Limbažu novads	85633279	LV	85686265
Latvia	Livanu novads	85633279	LV	85685943
Latvia	Lubanas novads	85633279	LV	85686131
Latvia	Ludzas novads	85633279	LV	85686037
Latvia	Madonas novads	85633279	LV	85686143
Latvia	Malpils novads	85633279	LV	85686099
Latvia	Marupes novads	85633279	LV	85686007
Latvia	Mazsalacas novads	85633279	LV	85686303
Latvia	Mersraga novads	85633279	LV	85686125
Latvia	Nauksenu novads	85633279	LV	85686299
Latvia	Neretas novads	85633279	LV	85685863
Latvia	Nicas novads	85633279	LV	85685791
Latvia	Ogres novads	85633279	LV	85686079
Latvia	Olaines novads	85633279	LV	85685915
Latvia	Olaines novads	85633279	LV	85685981
Latvia	Ozolnieku novads	85633279	LV	85685907
Latvia	Pargaujas novads	85633279	LV	85686215
Latvia	Pavilostas novads	85633279	LV	85685901
Latvia	Plavinu novads	85633279	LV	85686055
Latvia	Preilu novads	85633279	LV	85685929
Latvia	Priekules novads	85633279	LV	85685803
Latvia	Priekulu novads	85633279	LV	85686229
Latvia	Raunas novads	85633279	LV	85686225
Latvia	Raunas novads	85633279	LV	85686207
Latvia	Rezekne	85633279	LV	85686001
Latvia	Rezeknes novads	85633279	LV	85686095
Latvia	Riebinu novads	85633279	LV	85685977
Latvia	Riga	85633279	LV	85686065
Latvia	Rojas novads	85633279	LV	85686211
Latvia	Ropažu novads	85633279	LV	85686069
Latvia	Rucavas novads	85633279	LV	85685789
Latvia	Rugaju novads	85633279	LV	85686185
Latvia	Rujienas novads	85633279	LV	85686305
Latvia	Rundales novads	85633279	LV	85685845
Latvia	Salacgrivas novads	85633279	LV	85686287
Latvia	Salas novads	85633279	LV	85685953
Latvia	Salaspils novads	85633279	LV	85686015
Latvia	Saldus novads	85633279	LV	85685935
Latvia	Saulkrastu novads	85633279	LV	85686169
Latvia	Sejas novads	85633279	LV	85686161
Latvia	Siguldas novads	85633279	LV	85686135
Latvia	Skriveru novads	85633279	LV	85685975
Latvia	Skrundas novads	85633279	LV	85685871
Latvia	Smiltenes novads	85633279	LV	85686249
Latvia	Stopinu novads	85633279	LV	85686033
Latvia	Strencu novads	85633279	LV	85686275
Latvia	Talsu novads	85633279	LV	85686157
Latvia	Tervetes novads	85633279	LV	85685837
Latvia	Tukuma novads	85633279	LV	85686083
Latvia	Vainodes novads	85633279	LV	85685807
Latvia	Valkas novads	85633279	LV	85686295
Latvia	Valmiera	85633279	LV	85686243
Latvia	Varaklanu novads	85633279	LV	85686051
Latvia	Varkavas novads	85633279	LV	85685857
Latvia	Vecpiebalgas novads	85633279	LV	85686189
Latvia	Vecumnieku novads	85633279	LV	85685939
Latvia	Ventspils	85633279	LV	85686123
Latvia	Ventspils novads	85633279	LV	85686197
Latvia	Viesites novads	85633279	LV	85685875
Latvia	Vilakas novads	85633279	LV	85686251
Latvia	Vilanu novads	85633279	LV	85686049
Latvia	Zilupes novads	85633279	LV	85685987

**Comment by stepps00** [comment]
[Regions in Latvia](https://whosonfirst.mapzen.com/spelunker/id/85633279/descendants/?placetype=region&page=1#7/56.864/24.373) were edited in the commits above through a bulk update of new `wof:name` fields. The suffix of `novads` should now be removed from these records.

Closing issue.
