### ISSUE TITLE
Sweden region suffix is not necessary

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#56]
parent_name	name	parent_id	iso	id
Sweden	Blekinge län	85633789	SE	85688383
Sweden	Dalarnas län	85633789	SE	85688447
Sweden	Gävleborgs län	85633789	SE	85688453
Sweden	Gotlands län	85633789	SE	85688405
Sweden	Hallands län	85633789	SE	85688391
Sweden	Hovedstaden	85633789	DK	85682581
Sweden	Jämtlands län	85633789	SE	85688461
Sweden	Jämtlands län	85633789	SE	85688443
Sweden	Jönköpings län	85633789	SE	85688395
Sweden	Kalmar län	85633789	SE	85688401
Sweden	Kronobergs län	85633789	SE	85688387
Sweden	Norrbottens län	85633789	SE	85688471
Sweden	Örebro län	85633789	SE	85688421
Sweden	Östergötlands län	85633789	SE	85688409
Sweden	Skåne län	85633789	SE	85688377
Sweden	Södermanlands län	85633789	SE	85688419
Sweden	Stockholms län	85633789	SE	85688429
Sweden	Uppsala län	85633789	SE	85688439
Sweden	Värmlands län	85633789	SE	85688435
Sweden	Västerbottens län	85633789	SE	85688465
Sweden	Västernorrlands län	85633789	SE	85688457
Sweden	Västmanlands län	85633789	SE	85688425
Sweden	Västra Götalands län	85633789	SE	85688411

**Comment by hugovk** [comment]
Some of these have a possesive "s" at the end. In Swedish you put an "s" without an apostrophe, like English "'s". So "Dalarnas län" is literally "Dalarna's county".

Should these then be "Dalarna", "Gävleborg", etc.?

**Comment by nvkelso** [comment]
LGTM, thanks!

Let's track the separate bug about Sweden Hovedstaden 85633789 DK 85682581 with:
* https://github.com/whosonfirst/whosonfirst-data/issues/88
