### ISSUE TITLE
Finland region names should not include #

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#59]
Generally these are in the source to indicate language1#language2. Let's name it using the more conventional English name, and store the other names as alts.

Finland:
parent_name	name	parent_id	iso	id
Finland	Lappi#Lappland	85633143	FI	85683147
Finland	Kainuu#Kajanaland	85633143	FI	85683137
Finland	Uusimaa#Nyland	85633143	FI	85683067
Finland	Pirkanmaa#Birkaland	85633143	FI	85683099
Finland	Pohjanmaa#Österbotten	85633143	FI	85683119
Finland	Etelä-Savo#Södra Savolax	85633143	FI	85683109
Finland	Kanta-Häme#Egentliga Tavastland	85633143	FI	85683077
Finland	Keski-Suomi#Mellersta Finland	85633143	FI	85683117
Finland	Kymenlaakso#Kymmenedalen	85633143	FI	85683081
Finland	Päijät-Häme#Päijänne-Tavastland	85633143	FI	85683091
Finland	Päijät-Häme#Päijänne-Tavastland	85633143	FI	85683085
Finland	Pohjois-Savo#Norra Savolax	85633143	FI	85683131
Finland	Etelä-Karjala#Södra Karelen	85633143	FI	85683103
Finland	Etelä-Pohjanmaa#Södra Österbotten	85633143	FI	85683113
Finland	Keski-Pohjanmaa#Mellersta Österbotten	85633143	FI	85683125
Finland	Pohjois-Karjala#Norra Karelen	85633143	FI	85683133
Finland	Varsinais-Suomi#Egentliga Finland	85633143	FI	85683073
Finland	Pohjois-Pohjanmaa#Norra Österbotten	85633143	FI	85683143

**Comment by hugovk** [comment]
All of those are Finnish#Swedish. 

Finnish place names are generally used in English, but sometimes the Swedish is used officially, for example a town called Tammisaari in Finnish is Ekenäs in Swedish, and they use the Swedish officially, even if most Finnish speakers (and therefore most Finns) would use the Finnish when speaking English. 

However, many of the regions in this issue have English names too. 

Finland Lappi#Lappland 85633143 FI 85683147
Lapland
Finland Kainuu#Kajanaland 85633143 FI 85683137
Kainuu
Finland Uusimaa#Nyland 85633143 FI 85683067
Uusimaa
Finland Pirkanmaa#Birkaland 85633143 FI 85683099
Pirkanmaa
Finland Pohjanmaa#Österbotten 85633143 FI 85683119
Ostrobothnia
Finland Etelä-Savo#Södra Savolax 85633143 FI 85683109
Southern Savonia
Finland Kanta-Häme#Egentliga Tavastland 85633143 FI 85683077
Tavastia Proper
Finland Keski-Suomi#Mellersta Finland 85633143 FI 85683117
Central Finland
Finland Kymenlaakso#Kymmenedalen 85633143 FI 85683081
Kymenlaakso 
Finland Päijät-Häme#Päijänne-Tavastland 85633143 FI 85683091
Päijänne Tavastia
Finland Päijät-Häme#Päijänne-Tavastland 85633143 FI 85683085
Päijänne Tavastia
Finland Pohjois-Savo#Norra Savolax 85633143 FI 85683131
Northern Savonia
Finland Etelä-Karjala#Södra Karelen 85633143 FI 85683103
South Karelia
Finland Etelä-Pohjanmaa#Södra Österbotten 85633143 FI 85683113
Southern Ostrobothnia
Finland Keski-Pohjanmaa#Mellersta Österbotten 85633143 FI 85683125
Central Ostrobothnia
Finland Pohjois-Karjala#Norra Karelen 85633143 FI 85683133
North Karelia
Finland Varsinais-Suomi#Egentliga Finland 85633143 FI 85683073
Southwest Finland
Finland Pohjois-Pohjanmaa#Norra Österbotten 85633143 FI 85683143
Northern Ostrobothnia

**Comment by nvkelso** [comment]
@hugovk Thanks for the info!

Do you know what's up with:
Finland Päijät-Häme#Päijänne-Tavastland 85633143 FI 85683085
Päijänne Tavastia

It looks like a small chunk of the larger:
Finland Päijät-Häme#Päijänne-Tavastland 85633143 FI 85683091
Päijänne Tavastia

Should it be merged with the larger piece or is it special in some way?

**Comment by hugovk** [comment]
@nvkelso I think it should be merged.

You can see both parts in the maps of the region's website (see the NE bit of Heinola):

http://www.paijat-hame.fi/fi/maakunta/karttapohjia_paijat-hameesta

Google Maps also shows both parts:

https://www.google.com/maps/place/P%C3%A4ij%C3%A4nne+Tavastia,+Finland/@61.3404501,26.4810047,12.69z/data=!4m2!3m1!1s0x468fd1f4c5edcbdb:0xff99d2e9647c076f

And for verification, the other region (Southern Savonia) is has that chunk missing as expected:

https://github.com/whosonfirst/whosonfirst-data/blob/master/data/856/831/09/85683109.geojson

**Comment by nvkelso** [comment]
Interesting, will mark for merging. There are a few of these situations in the European data, so its not totally unexpected. 

I wonder what makes this exclave special?

**Comment by hugovk** [comment]
I've no idea, the only place name inside it on GMaps is Mäntyranta, which means "pine beach". There's no shortage of pine trees or lakes in any part of Finland. Perhaps it's a particularly fine spot for holiday cottages...

I'll try and find out!

**Comment by hugovk** [comment]
@nvkelso I [asked a librarian](http://www.libraries.fi/en-GB/ask/) about [the enclave](https://www.google.com/maps/place/P%C3%A4ij%C3%A4nne+Tavastia,+Finland/@61.3387748,26.4830799,6298m/data=!3m1!1e3!4m2!3m1!1s0x468fd1f4c5edcbdb:0xff99d2e9647c076f), here's their  answer:

> I didn't receive an answer from Heinola [library] yet, but I found an Internet site, that contains some knowledge about the history of the Enonvesi-region and its villages, http://www.enonkylat.fi/historiikki/. As far as I understand, part of the area has belonged to the cultural region of Häme from early on, the fiscal authorities and the nearest church have been in Häme. That could probably be the explanation to the fact that this part, called Paadenmaa, still belongs to Päijät-Häme [aka Päijänne Tavastia] and not to South-Savonia.

> The history of Enonvesi villages is written by Anne Piira. I'll try to find her contact information.
