### ISSUE TITLE
United Kingdom region names should not include #

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#60]
Generally these are in the source to indicate language1#language2. Let's name it using the more conventional English name, and store the other names as alts.

parent_name	name	parent_id	iso	id
United Kingdom	Conwy#Conwy	85633159	GB	85684317
United Kingdom	Powys#Powys	85633159	GB	85683965
United Kingdom	Gwynedd#Gwynedd	85633159	GB	85684205
United Kingdom	Wrecsam#Wrexham	85633159	GB	85684575
United Kingdom	Abertawe#Swansea	85633159	GB	85684551
United Kingdom	Caerdydd#Cardiff	85633159	GB	85683787
United Kingdom	Tor-faen#Torfaen	85633159	GB	85684181
United Kingdom	Caerffili#Caerphilly	85633159	GB	85684187
United Kingdom	Casnewydd#Newport	85633159	GB	85684571
United Kingdom	Sir Fynwy#Monmouthshire	85633159	GB	85684303
United Kingdom	Sir Benfro#Pembrokeshire	85633159	GB	85683613
United Kingdom	Sir Ddinbych#Denbighshire	85633159	GB	85684343
United Kingdom	Sir y Fflint#Flintshire	85633159	GB	85683839
United Kingdom	Sir Ynys Mon#Isle of Anglesey	85633159	GB	85683833
United Kingdom	Blaenau Gwent#Blaenau Gwent	85633159	GB	85683983
United Kingdom	Bro Morgannwg#the Vale of Glamorgan	85633159	GB	85683913
United Kingdom	Merthyr Tudful#Merthyr Tydfil	85633159	GB	85684355
United Kingdom	Sir Ceredigion#Ceredigion	85633159	GB	85684307
United Kingdom	Sir Gaerfyrddin#Carmarthenshire	85633159	GB	85684603
United Kingdom	Pen-y-bont ar Ogwr#Bridgend	85633159	GB	85684263
United Kingdom	Rhondda, Cynon, Taf#Rhondda, Cynon, Taff	85633159	GB	85683991
United Kingdom	Castell-nedd Port Talbot#Neath Port Talbot	85633159	GB	85684117

**Comment by hugovk** [comment]
These are all in Wales and are Welsh#English (or Welsh#Welsh-but-same-name-is-used-in-English).

**Comment by nvkelso** [comment]
Thanks!

**Comment by hugovk** [comment]
@nvkelso What keys should be for the main, English name, and for the alternative, Welsh name?
