### ISSUE TITLE
Locality quattroshapes encoding issues

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-data#69]
this ticket is to track encoding issues reported by the Pelias team relating to data sourced from the quattroshapes project on/before 1 sept 2015

https://github.com/pelias/quattroshapes-patch/issues/10
https://github.com/pelias/quattroshapes-patch/issues/9
https://github.com/pelias/pelias/issues/82

**Comment by nvkelso** [comment]
Regarding:
pelias/quattroshapes-patch#10

Example 1:
http://pelias.mapzen.com/doc?id=osmnode:3485575196
pelias_locality: ÎÎÎÎÎÎ
wof_locality: ΑΘΗΝΑΙ
wof_id: 101913513

Example 2:
http://pelias.mapzen.com/doc?id=osmway:228966671
pelias_locality: DzierÅ¼oniÃ³w
wof_locality: DzierÅ¼oniowski
wof_id: 102079591

**Comment by nvkelso** [comment]
Regarding:
pelias/quattroshapes-patch#9

Example 1:
http://pelias.mapzen.com/search?input=culture%20espresso
pelias_locality: MariÃ¡nskÃ© LÃ¡znÄ�
wof_locality: Mariánské Lázně
wof_id: 101825353

**Comment by nvkelso** [comment]
Regarding:
pelias/pelias#82

Example 1: 
pelias_locality: Î�ï�î¿ï�î·î³î® (in Λεμεσός)
wof_locality: Paramali or Ακρωτήρι or Τραχώνι
wof_id: either 101911237 or 101804657 or 101804663

Example 2:
http://pelias.mapzen.com/doc?id=locality:71125:locality:de:deu:m__nchenbernsdorf
pelias_locality: Mã¼nchenbernsdorf
wof_locality: Münchenbernsdorf
wof_id: 101823185

Example 3:
[https://camo.githubusercontent.com/ef31904be8cfbca119903356e7b627bca4c27e70/687474703a2f2f70657465722e6a6f686e736f6e2e73332e616d617a6f6e6177732e636f6d2f636861725f656e636f64696e672e706e67]
Zurich / Zürichhorn

**Comment by nvkelso** [comment]
Except for wof_locality: DzierÅ¼oniowski (wof_id: 102079591) and the fix already proposed in #49 for admin-2-county names, these look good in Who's On First.

Which makes me suspect there are character encoding errors in the Pelias pipeline.

**Comment by stepps00** [comment]
Closing this until further reports.
