### ISSUE TITLE
Hovedstaden is in Denmark (not Sweden)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#88]
Looks like our rev-geo for this one has an error:
Sweden Hovedstaden 85633789 DK 85682581

Note the country name and the country code don't match up. We should probably add a test for this.

Because the feature is a series of discontinuous islands, the math centroid isn't snapped inside of one of those, and happens to fall over Sweden. Oops.

**Comment by stepps00** [comment]
Looks like this issue was taken care of in Issue #255 and Issue #254, 

@nvkelso OK to close?

**Comment by nvkelso** [comment]
Yep.
